### ISSUE TITLE
Sends me to safemode

### ISSUE THREAD

**Issue by fenntastic** [MatoiDev/Witcher#4]
...when I use a drag down function from NiceBarX tweak to kill all apps. 

Love your tweak. 
Just let me know, if you need any further information.

rootless, dopamine, iPhoneXS, iOS 15.1

**Comment by fenntastic** [comment]
It's the same when I use Lynx2 tweak for the same function.

**Comment by fenntastic** [comment]
Here is a KrashKop log file:

Incident Identifier: 4CA59641-9E04-4993-BD6C-74FEDC4A2E41
CrashReporter Key:   f90f914fea38d2c76f65ab6287496935446ee337
Hardware Model:      iPhone11,2
Process:             SpringBoard [2580]
Path:                /System/Library/CoreServices/SpringBoard.app/SpringBoard
Identifier:          com.apple.springboard
Version:             1.0 (50)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.apple.springboard [529]

Date/Time:           2024-07-04 23:39:19.0097 +0200
Launch Time:         2024-07-04 23:31:49.1977 +0200
OS Version:          iPhone OS 15.1 (19B74)
Release Type:        User
Baseband Version:    4.02.02
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Application Specific Information:



abort() called


Last Exception Backtrace:
0   CoreFoundation                	       0x18078904c __exceptionPreprocess + 220
1   libobjc.A.dylib               	       0x198dfdf54 objc_exception_throw + 60
2   CoreFoundation                	       0x180866014 +[NSObject(NSObject) _copyDescription] + 0
3   UIKitCore                     	       0x183aff5a0 -[UIResponder doesNotRecognizeSelector:] + 296
4   CoreFoundation                	       0x18071e474 ___forwarding___ + 1728
5   CoreFoundation                	       0x18071d5b0 _CF_forwarding_prep_0 + 96
6   Witcher.dylib                 	       0x103fad3b8 0x103fa8000 + 21432
7   Lynx.dylib                    	       0x103a35004 0x103a04000 + 200708
8   Lynx.dylib                    	       0x103a341dc 0x103a04000 + 197084
9   UIKitCore                     	       0x183127538 -[UIScrollView _performScrollViewWillEndDraggingInvocationsWithVelocity:targetContentOffset:unclampedOriginalTarget:] + 316
10  UIKitCore                     	       0x1831a4628 -[UIScrollView _scrollViewWillEndDraggingWithDeceleration:] + 1096
11  UIKitCore                     	       0x182fe0d9c -[UIScrollView _endPanNormal:] + 2248
12  UIKitCore                     	       0x182e3e840 -[UIScrollView handlePan:] + 192
13  UIKitCore                     	       0x182d7642c -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 56
14  UIKitCore                     	       0x182d3f560 _UIGestureRecognizerSendTargetActions + 116
15  UIKitCore                     	       0x182d08260 _UIGestureRecognizerSendActions + 284
16  UIKitCore                     	       0x182d41910 -[UIGestureRecognizer _updateGestureForActiveEvents] + 636
17  UIKitCore                     	       0x182cf9ad0 _UIGestureEnvironmentUpdate + 1988
18  UIKitCore                     	       0x182d2d8c8 -[UIGestureEnvironment _updateForEvent:window:] + 784
19  UIKitCore                     	       0x182d3aa68 -[UIWindow sendEvent:] + 4428
20  UIKitCore                     	       0x182eea318 -[UIApplication sendEvent:] + 828
21  UIKit                         	       0x1f0c9b414 -[UIApplicationAccessibility sendEvent:] + 100
22  UIKitCore                     	       0x182d0dc30 __dispatchPreprocessedEventFromEventQueue + 7904
23  UIKitCore                     	       0x182d02a1c __processEventQueue + 6760
24  UIKitCore                     	       0x182d07ec8 __eventFetcherSourceCallback + 172
25  CoreFoundation                	       0x1807ab020 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
26  CoreFoundation                	       0x1807bbce0 __CFRunLoopDoSource0 + 208
27  CoreFoundation                	       0x1806f5fe8 __CFRunLoopDoSources0 + 268
28  CoreFoundation                	       0x1806fb7f4 __CFRunLoopRun + 820
29  CoreFoundation                	       0x18070f3b8 CFRunLoopRunSpecific + 600
30  GraphicsServices              	       0x19c09f38c GSEventRunModal + 164
31  UIKitCore                     	       0x1830af6a8 -[UIApplication _run] + 1100
32  UIKitCore                     	       0x182e2e7f4 UIApplicationMain + 2092
33  SpringBoard                   	       0x1ad599730 SBSystemAppMain + 6564
34  dyld                          	       0x100379a24 start + 520

Kernel Triage:
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get


Thread 0 name:   Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	       0x1b75d0964 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x1f0a30378 pthread_kill + 268
2   libsystem_c.dylib             	       0x18b5c6f50 abort + 164
3   libc++abi.dylib               	       0x198f05bc4 abort_message + 132
4   libc++abi.dylib               	       0x198ef6fd8 demangling_terminate_handler() + 332
5   libobjc.A.dylib               	       0x198e04064 _objc_terminate() + 144
6   libc++abi.dylib               	       0x198f04f58 std::__terminate(void (*)()) + 20
7   libc++abi.dylib               	       0x198f07efc __cxa_rethrow + 148
8   libobjc.A.dylib               	       0x198dffe8c objc_exception_rethrow + 44
9   CoreFoundation                	       0x18070f4a4 CFRunLoopRunSpecific + 836
10  GraphicsServices              	       0x19c09f38c GSEventRunModal + 164
11  UIKitCore                     	       0x1830af6a8 -[UIApplication _run] + 1100
12  UIKitCore                     	       0x182e2e7f4 UIApplicationMain + 2092
13  SpringBoard                   	       0x1ad599730 SBSystemAppMain + 6564
14  dyld                          	       0x100379a24 start + 520

Thread 1 name:  AVAudioSession Notify Thread
Thread 1:
0   libsystem_kernel.dylib        	       0x1b75ca504 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1b75cab9c mach_msg + 76
2   CoreFoundation                	       0x1806f7688 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x1806fb97c __CFRunLoopRun + 1212
4   CoreFoundation                	       0x18070f3b8 CFRunLoopRunSpecific + 600
5   AudioSession                  	       0x189aa3308 CADeprecated::GenericRunLoopThread::Entry(void*) + 164
6   AudioSession                  	       0x189aacd64 CADeprecated::CAPThread::Entry(CADeprecated::CAPThread*) + 92
7   libsystem_pthread.dylib       	       0x1f0a2a9a4 _pthread_start + 148
8   libsystem_pthread.dylib       	       0x1f0a29ea0 thread_start + 8

Thread 2 name:  com.apple.uikit.eventfetch-thread
Thread 2:
0   libsystem_kernel.dylib        	       0x1b75ca504 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1b75cab9c mach_msg + 76
2   CoreFoundation                	       0x1806f7688 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x1806fb97c __CFRunLoopRun + 1212
4   CoreFoundation                	       0x18070f3b8 CFRunLoopRunSpecific + 600
5   Foundation                    	       0x181f2a354 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
6   Foundation                    	       0x181f6bc28 -[NSRunLoop(NSRunLoop) runUntilDate:] + 92
7   UIKitCore                     	       0x1830288a4 -[UIEventFetcher threadMain] + 524
8   Foundation                    	       0x181f7a36c __NSThread__start__ + 808
9   libsystem_pthread.dylib       	       0x1f0a2a9a4 _pthread_start + 148
10  libsystem_pthread.dylib       	       0x1f0a29ea0 thread_start + 8

Thread 3 name:  com.apple.NSURLConnectionLoader
Thread 3:
0   libsystem_kernel.dylib        	       0x1b75ca504 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1b75cab9c mach_msg + 76
2   CoreFoundation                	       0x1806f7688 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x1806fb97c __CFRunLoopRun + 1212
4   CoreFoundation                	       0x18070f3b8 CFRunLoopRunSpecific + 600
5   CFNetwork                     	       0x1811836a0 0x180f09000 + 2598560
6   Foundation                    	       0x181f7a36c __NSThread__start__ + 808
7   libsystem_pthread.dylib       	       0x1f0a2a9a4 _pthread_start + 148
8   libsystem_pthread.dylib       	       0x1f0a29ea0 thread_start + 8

Thread 4 name:  com.apple.CoreMotion.MotionThread
Thread 4:
0   libsystem_kernel.dylib        	       0x1b75ca504 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1b75cab9c mach_msg + 76
2   CoreFoundation                	       0x1806f7688 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x1806fb97c __CFRunLoopRun + 1212
4   CoreFoundation                	       0x18070f3b8 CFRunLoopRunSpecific + 600
5   CoreFoundation                	       0x18078fa78 CFRunLoopRun + 64
6   CoreMotion                    	       0x18d6ef544 0x18d6dc000 + 79172
7   libsystem_pthread.dylib       	       0x1f0a2a9a4 _pthread_start + 148
8   libsystem_pthread.dylib       	       0x1f0a29ea0 thread_start + 8

Thread 5 name:  SBWiFiManager callback thread
Thread 5:
0   libsystem_kernel.dylib        	       0x1b75ca504 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1b75cab9c mach_msg + 76
2   CoreFoundation                	       0x1806f7688 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x1806fb97c __CFRunLoopRun + 1212
4   CoreFoundation                	       0x18070f3b8 CFRunLoopRunSpecific + 600
5   Foundation                    	       0x181f2a354 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
6   Foundation                    	       0x181f2ab10 -[NSRunLoop(NSRunLoop) run] + 92
7   SpringBoard                   	       0x1ad6dd59c -[SBWiFiManager _runManagerCallbackThread] + 268
8   Foundation                    	       0x181f7a36c __NSThread__start__ + 808
9   libsystem_pthread.dylib       	       0x1f0a2a9a4 _pthread_start + 148
10  libsystem_pthread.dylib       	       0x1f0a29ea0 thread_start + 8

Thread 6 name:  WFPersonalHotspotStateMonitor callback thread
Thread 6:
0   libsystem_kernel.dylib        	       0x1b75ca504 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1b75cab9c mach_msg + 76
2   CoreFoundation                	       0x1806f7688 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x1806fb97c __CFRunLoopRun + 1212
4   CoreFoundation                	       0x18070f3b8 CFRunLoopRunSpecific + 600
5   Foundation                    	       0x181f2a354 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
6   Foundation                    	       0x181f2ab10 -[NSRunLoop(NSRunLoop) run] + 92
7   WiFiKit                       	       0x1babdff0c -[WFPersonalHotspotStateMonitor _runManagerCallbackThread] + 448
8   Foundation                    	       0x181f7a36c __NSThread__start__ + 808
9   libsystem_pthread.dylib       	       0x1f0a2a9a4 _pthread_start + 148
10  libsystem_pthread.dylib       	       0x1f0a29ea0 thread_start + 8

Thread 7 name:   Dispatch queue: com.niceios.myipc-messageQueue
Thread 7:
0   libsystem_kernel.dylib        	       0x1b75ca504 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1b75cab9c mach_msg + 76
2   BarXSBoard.dylib              	       0x103d25eb8 0x103af4000 + 2301624
3   libdispatch.dylib             	       0x1803f9914 _dispatch_call_block_and_release + 32
4   libdispatch.dylib             	       0x1803fb660 _dispatch_client_callout + 20
5   libdispatch.dylib             	       0x180402de4 _dispatch_lane_serial_drain + 672
6   libdispatch.dylib             	       0x180403958 _dispatch_lane_invoke + 392
7   libdispatch.dylib             	       0x18040e1a8 _dispatch_workloop_worker_thread + 656
8   libsystem_pthread.dylib       	       0x1f0a2a0f4 _pthread_wqthread + 288
9   libsystem_pthread.dylib       	       0x1f0a29e94 start_wqthread + 8

Thread 8 name:   Dispatch queue: com.niceios.myipc-messageQueue
Thread 8:
0   libsystem_kernel.dylib        	       0x1b75ca504 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1b75cab9c mach_msg + 76
2   NiceCaller.dylib              	       0x10429e5ec 0x1041ec000 + 730604
3   libdispatch.dylib             	       0x1803f9914 _dispatch_call_block_and_release + 32
4   libdispatch.dylib             	       0x1803fb660 _dispatch_client_callout + 20
5   libdispatch.dylib             	       0x180402de4 _dispatch_lane_serial_drain + 672
6   libdispatch.dylib             	       0x180403958 _dispatch_lane_invoke + 392
7   libdispatch.dylib             	       0x18040e1a8 _dispatch_workloop_worker_thread + 656
8   libsystem_pthread.dylib       	       0x1f0a2a0f4 _pthread_wqthread + 288
9   libsystem_pthread.dylib       	       0x1f0a29e94 start_wqthread + 8

Thread 9 name:  CommonUtilities-WiFi-Thread
Thread 9:
0   libsystem_kernel.dylib        	       0x1b75ca504 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1b75cab9c mach_msg + 76
2   CoreFoundation                	       0x1806f7688 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x1806fb97c __CFRunLoopRun + 1212
4   CoreFoundation                	       0x18070f3b8 CFRunLoopRunSpecific + 600
5   CoreFoundation                	       0x18078fa78 CFRunLoopRun + 64
6   CommonUtilities               	       0x191dc8ed0 0x191db9000 + 65232
7   Foundation                    	       0x181f7a36c __NSThread__start__ + 808
8   libsystem_pthread.dylib       	       0x1f0a2a9a4 _pthread_start + 148
9   libsystem_pthread.dylib       	       0x1f0a29ea0 thread_start + 8

Thread 10 name:  com.apple.UIKit.inProcessAnimationManager Dispatch queue: com.apple.UIKit.inProcessAnimationManagerTickQueue
Thread 10:
0   libsystem_kernel.dylib        	       0x1b75ca558 semaphore_timedwait_trap + 8
1   libdispatch.dylib             	       0x1803fbc6c _dispatch_sema4_timedwait + 64
2   libdispatch.dylib             	       0x1803fc270 _dispatch_semaphore_wait_slow + 76
3   UIKitCore                     	       0x182d20564 -[UIViewInProcessAnimationManager _processPostTicksDelayIfNecessary:] + 148
4   UIKitCore                     	       0x182d1b3c8 __82-[UIViewInProcessAnimationManager _performTick:cancel:force:eventName:entry:exit:]_block_invoke + 320
5   libdispatch.dylib             	       0x1803fb660 _dispatch_client_callout + 20
6   libdispatch.dylib             	       0x18040a8b4 _dispatch_lane_barrier_sync_invoke_and_complete + 56
7   UIKitCore                     	       0x182d1f214 -[UIViewInProcessAnimationManager _performTick:cancel:force:eventName:entry:exit:] + 248
8   UIKitCore                     	       0x182d1bfec -[UIViewInProcessAnimationManager _displayLinkFire:] + 216
9   QuartzCore                    	       0x184450d90 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 756
10  QuartzCore                    	       0x1844576dc display_timer_callback(__CFMachPort*, void*, long, void*) + 372
11  CoreFoundation                	       0x1806fb390 __CFMachPortPerform + 176
12  CoreFoundation                	       0x18073e724 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 60
13  CoreFoundation                	       0x180741f30 __CFRunLoopDoSource1 + 596
14  CoreFoundation                	       0x1806fbe0c __CFRunLoopRun + 2380
15  CoreFoundation                	       0x18070f3b8 CFRunLoopRunSpecific + 600
16  Foundation                    	       0x181f2a354 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
17  Foundation                    	       0x181f2ab10 -[NSRunLoop(NSRunLoop) run] + 92
18  UIKitCore                     	       0x182e56b70 __66-[UIViewInProcessAnimationManager startAdvancingAnimationManager:]_block_invoke_3 + 168
19  Foundation                    	       0x181f7a36c __NSThread__start__ + 808
20  libsystem_pthread.dylib       	       0x1f0a2a9a4 _pthread_start + 148
21  libsystem_pthread.dylib       	       0x1f0a29ea0 thread_start + 8

Thread 11 name:  WFWiFiStateMonitor callback thread
Thread 11:
0   libsystem_kernel.dylib        	       0x1b75ca504 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1b75cab9c mach_msg + 76
2   CoreFoundation                	       0x1806f7688 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x1806fb97c __CFRunLoopRun + 1212
4   CoreFoundation                	       0x18070f3b8 CFRunLoopRunSpecific + 600
5   Foundation                    	       0x181f2a354 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
6   Foundation                    	       0x181f2ab10 -[NSRunLoop(NSRunLoop) run] + 92
7   WiFiKit                       	       0x1babcd8ec -[WFWiFiStateMonitor _runManagerCallbackThread] + 280
8   Foundation                    	       0x181f7a36c __NSThread__start__ + 808
9   libsystem_pthread.dylib       	       0x1f0a2a9a4 _pthread_start + 148
10  libsystem_pthread.dylib       	       0x1f0a29ea0 thread_start + 8

Thread 12 name:  WFPersonalHotspotStateMonitor callback thread
Thread 12:
0   libsystem_kernel.dylib        	       0x1b75ca504 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1b75cab9c mach_msg + 76
2   CoreFoundation                	       0x1806f7688 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x1806fb97c __CFRunLoopRun + 1212
4   CoreFoundation                	       0x18070f3b8 CFRunLoopRunSpecific + 600
5   Foundation                    	       0x181f2a354 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
6   Foundation                    	       0x181f2ab10 -[NSRunLoop(NSRunLoop) run] + 92
7   WiFiKit                       	       0x1babdff0c -[WFPersonalHotspotStateMonitor _runManagerCallbackThread] + 448
8   Foundation                    	       0x181f7a36c __NSThread__start__ + 808
9   libsystem_pthread.dylib       	       0x1f0a2a9a4 _pthread_start + 148
10  libsystem_pthread.dylib       	       0x1f0a29ea0 thread_start + 8

Thread 13:
0   libsystem_pthread.dylib       	       0x1f0a29e8c start_wqthread + 0

Thread 14:
0   libsystem_pthread.dylib       	       0x1f0a29e8c start_wqthread + 0

Thread 15:
0   libsystem_pthread.dylib       	       0x1f0a29e8c start_wqthread + 0

Thread 16:
0   libsystem_pthread.dylib       	       0x1f0a29e8c start_wqthread + 0

Thread 17:
0   libsystem_pthread.dylib       	       0x1f0a29e8c start_wqthread + 0

Thread 18:
0   libsystem_pthread.dylib       	       0x1f0a29e8c start_wqthread + 0

Thread 19:
0   libsystem_pthread.dylib       	       0x1f0a29e8c start_wqthread + 0

Thread 20:
0   libsystem_pthread.dylib       	       0x1f0a29e8c start_wqthread + 0

Thread 21:
0   libsystem_pthread.dylib       	       0x1f0a29e8c start_wqthread + 0

Thread 22:
0   libsystem_pthread.dylib       	       0x1f0a29e8c start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000198f090ad   x5: 0x000000016fd46c80   x6: 0x000000000000006e   x7: 0xffffffff000dea00
    x8: 0xef47fd008a2da670   x9: 0xef2726018a11e3f0  x10: 0x0000000000000002  x11: 0x000000000000000b
   x12: 0x00000000bee25873  x13: 0x000000003ee25800  x14: 0x0000000000000010  x15: 0x0000000000000002
   x16: 0x0000000000000148  x17: 0x00000001003c4580  x18: 0x000000010ff93940  x19: 0x0000000000000006
   x20: 0x0000000000000103  x21: 0x00000001003c4660  x22: 0x0000000000000001  x23: 0x0000000282586640
   x24: 0x0000000000000000  x25: 0x0000000000000001  x26: 0x0000000eb1e31100  x27: 0x00000001d9eaa000
   x28: 0x0000000000000001   fp: 0x000000016fd46bf0   lr: 0x00000001f0a30378
    sp: 0x000000016fd46bd0   pc: 0x00000001b75d0964 cpsr: 0x40000000
   far: 0x00000001f07459ec  esr: 0x56000080  Address size fault

Binary Images:
       0x1b75c9000 -        0x1b75fcfff libsystem_kernel.dylib arm64e  <b1b942de75903c61980a19d80ed4da37> /usr/lib/system/libsystem_kernel.dylib
       0x1f0a29000 -        0x1f0a34fff libsystem_pthread.dylib arm64e  <1a4a45fd1bb639df84140590ce103717> /usr/lib/system/libsystem_pthread.dylib
       0x18b5a7000 -        0x18b625fff libsystem_c.dylib arm64e  <30a1668a329d30009f747b42b21fe0fd> /usr/lib/system/libsystem_c.dylib
       0x198ef2000 -        0x198f0bfff libc++abi.dylib arm64e  <375cf7503f9339e8a6eb1c0d7181c64e> /usr/lib/libc++abi.dylib
       0x198de8000 -        0x198e21fff libobjc.A.dylib arm64e  <10fa90c6dfe538aeb3dc2251181cc272> /usr/lib/libobjc.A.dylib
       0x1806f0000 -        0x180b43fff CoreFoundation arm64e  <b2d21cfd378c36d5baf73f70599cfefc> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
       0x19c09e000 -        0x19c0a6fff GraphicsServices arm64e  <44e4515eb18737f18fe028e7b087daf5> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
       0x182b96000 -        0x18441afff UIKitCore arm64e  <8388eb03002b3b35a78a6a022894292e> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
       0x1ad4ba000 -        0x1adedefff SpringBoard arm64e  <1f65bed825da33e9992c579ccdf34265> /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
       0x100360000 -        0x1003b7fff dyld arm64e  <444f50414d494e45444f50414d494e45> /usr/lib/dyld
       0x189a9d000 -        0x189ac6fff AudioSession arm64e  <99ff741f34943edf82b7c03c916ebad3> /System/Library/PrivateFrameworks/AudioSession.framework/AudioSession
       0x181f12000 -        0x182217fff Foundation arm64e  <d59c69755af237bc93be43b80b4293a5> /System/Library/Frameworks/Foundation.framework/Foundation
       0x180f09000 -        0x1813cdfff CFNetwork arm64e  <1f9e80ee1df136acbdfe22afb9a1b82e> /System/Library/Frameworks/CFNetwork.framework/CFNetwork
       0x18d6dc000 -        0x18d9e8fff CoreMotion arm64e  <7464cd4b1ec7342392ce51becea40ca3> /System/Library/Frameworks/CoreMotion.framework/CoreMotion
       0x1bab69000 -        0x1bac43fff WiFiKit arm64e  <2a5c5fa1d19c3f4ab2e85409ed627e8f> /System/Library/PrivateFrameworks/WiFiKit.framework/WiFiKit
       0x103af4000 -        0x103d7ffff BarXSBoard.dylib arm64e  <0014f414f6023a24909ae26d9923789e> /private/preboot/180A9ADD8555A1B5B7179378F90D2AB18E3D57FA80BB5F96E0DC3C825BA98BE5B66D1D2179CAB7F134C5801358F88E82/dopamine-DQveUU/procursus/usr/lib/TweakInject/BarXSBoard.dylib
       0x1803f7000 -        0x18043dfff libdispatch.dylib arm64e  <a5cbaab3e3893548baacfab18411b94a> /usr/lib/system/libdispatch.dylib
       0x1041ec000 -        0x10434bfff NiceCaller.dylib arm64e  <fbeb411437083a698dd443fa8df99cb7> /private/preboot/180A9ADD8555A1B5B7179378F90D2AB18E3D57FA80BB5F96E0DC3C825BA98BE5B66D1D2179CAB7F134C5801358F88E82/dopamine-DQveUU/procursus/usr/lib/TweakInject/NiceCaller.dylib
       0x191db9000 -        0x191dd7fff CommonUtilities arm64e  <4621e86974c231f2bcf63eba8fe402b9> /System/Library/PrivateFrameworks/CommonUtilities.framework/CommonUtilities
       0x184440000 -        0x184725fff QuartzCore arm64e  <39e0ffb211c431c198e04330b3a2cc3b> /System/Library/Frameworks/QuartzCore.framework/QuartzCore
       0x103fa8000 -        0x103fbbfff Witcher.dylib arm64e  <57fe30c4059833f6bc39d52c44dac75d> /private/preboot/180A9ADD8555A1B5B7179378F90D2AB18E3D57FA80BB5F96E0DC3C825BA98BE5B66D1D2179CAB7F134C5801358F88E82/dopamine-DQveUU/procursus/usr/lib/TweakInject/Witcher.dylib
       0x103a04000 -        0x103a63fff Lynx.dylib arm64e  <abc6e69b13d53ceebc5ab80a92ea5e7a> /private/preboot/180A9ADD8555A1B5B7179378F90D2AB18E3D57FA80BB5F96E0DC3C825BA98BE5B66D1D2179CAB7F134C5801358F88E82/dopamine-DQveUU/procursus/usr/lib/TweakInject/Lynx.dylib
       0x1f0c69000 -        0x1f0da2fff UIKit arm64e  <e9cfea6b212137b3bbe3b940cd5959c7> /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

EOF

**Comment by MatoiDev** [comment]
Hello, sir!
Big thanks for providing the the detailed information! The bug has been fixed in the [new release](https://github.com/MatoiDev/Witcher/releases/tag/v1.0.0-public). The update is currently under moderation on Havoc, but you can already [download it](https://github.com/MatoiDev/Witcher/releases/tag/v1.0.0-public) from this repository.

**Comment by fenntastic** [comment]
Thanks a lot.
