### ISSUE TITLE
Can iOS 15.7+ be supported?

### ISSUE THREAD

**Issue by F1248** [MatoiDev/Witcher#5]
Are there any reasons why Witcher depends on firmware <= 15.6.1? Would it be possible to support iOS 15.8.2?
Thanks for this great tweak!

**Comment by MatoiDev** [comment]
Hi
The thing is that ios 15.8.x is Apple's shitty attempt to integrate ios 16 classes into unsupported devices such as iphone 7, unfortunately the good old AppSwitcher has been replaced by the new Coordinator class from iOS 16, so Wither doesn't work on this os. When I get an ios 16 jailbroken device, I will definitely add support for ios 15.8.x & 16.x.x.

**Comment by F1248** [comment]
Thanks for your answer, I understand and will wait for the update!
